### ISSUE TITLE
An other error 

### ISSUE THREAD

**Issue by ghost** [Infernus101/ProfileUI#15]
```CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerDeathEvent' to 'ProfileUI v3.5.1': Event is not Cancellable on Infernus101\PlayerEvents                                        [11:41:10] [Server thread/CRITICAL]: BadMethodCallException: "Event is not Cancellable" (EXCEPTION) in "src/pocketmine/event/Event" at line 58```

**Comment by Infernus101** [comment]
Please provide more information

**Comment by ghost** [comment]
When i kill m'y self (in-game XD) console say this error ⬆
They are greate chance is this event https://github.com/Infernus101/ProfileUI/blob/master/src/Infernus101/PlayerEvents.php#L40

**Comment by Infernus101** [comment]
How are you killing yourself?

**Comment by ghost** [comment]
when I jump on a staircase and run right after I die instantly

PmmP issu !!

**Comment by Infernus101** [comment]
try this
