### ISSUE TITLE
Error again

### ISSUE THREAD

**Issue by ghost** [Infernus101/ProfileUI#20]
`[12:04:27] [Server thread/CRITICAL]: Unhandled exception executing command 'profile armthedev' in profile: Undefined index: mining
[12:04:27] [Server thread/CRITICAL]: ErrorException: "Undefined index: mining" (EXCEPTION) in "ProfileUI-master/src/Infernus101/window/ProfileWindow" at line 68`

This happen when /profile [name]

**Comment by Infernus101** [comment]
please mention the commit you are using and paste the config.

**Comment by ghost** [comment]
ab8f762

**Comment by Infernus101** [comment]
config?

**Comment by ghost** [comment]
Idk i will retry.

And plz add task because kill and deather doesnt refresh .

**Comment by Infernus101** [comment]
um yes it does..

**Comment by ghost** [comment]
When i kill m'y self by /kill
`[12:36:55] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerDeathEvent' to 'ProfileUI v4': Call to undefined method pocketmine\event\entity\EntityDamageEvent::getDamager() on Infernus101\PlayerEvents                                                            [12:36:55] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\event\entity\EntityDamageEvent::getDamager()" (EXCEPTION) in "ProfileUI-master/src/Infernus101/PlayerEvents" at line 42  `

**Comment by Infernus101** [comment]
use latest commit and check

**Comment by ghost** [comment]
Same error of #21

**Comment by Infernus101** [comment]
fixed?

**Comment by ghost** [comment]
Fixes and #21 same
