### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by VoxCeleste** [Infernus101/ProfileUI#24]
I have a customui,my question is..What command/code do i have to put on an item that when you tap for example the book(My profile) It will show you your profile?

**Comment by Infernus101** [comment]
$offplayer= $this->getServer()->getOfflinePlayer("PLAYER USERNAME TO SEE PROFILE OF");
if(!is_numeric($offplayer->getFirstPlayed())){
 $sender->sendMessage(TextFormat::RED."Error > Player not found");
					return false;
				}
				$handler = new Handler();
				$packet = new ModalFormRequestPacket();
				$packet->formId = $handler->getWindowIdFor(Handler::PROFILE_WINDOW);
				$packet->formData = $handler->getWindowJson(Handler::PROFILE_WINDOW, $this, $sender, $offplayer);
				$sender->dataPacket($packet);
