### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by ghost** [Infernus101/ProfileUI#26]
I want a slapper to use /profile without the player manually typing /profile then their name.

For Example, i want the player to hit a slapper using rca {player} profile and the profile UI shows

**Comment by Infernus101** [comment]
so just addcommand rca {player} profile {player}

**Comment by ghost** [comment]
I did that already

**Comment by Infernus101** [comment]
what does it say then?

**Comment by ghost** [comment]
Nothing happens, not even in console.
