### ISSUE TITLE
More Ideas

### ISSUE THREAD

**Issue by TwistedAsylumMC** [Infernus101/ProfileUI#9]
Currently, Its Basically Only For Factions! Im Sure Other Types Of Servers Want To Use It But The Current Features Don't Really Match Their Server! To Fix This I Have Some Ideas:

Prisons:
- [x] Total Blocks Broke

Sky Wars:
- [ ] Games Won

All:
- [x] K/D Ratio
- [x] Kill Count
- [x] Death Count

**Comment by Infernus101** [comment]
Easy

**Comment by Infernus101** [comment]
Don't know about skywars though, which skywars plugin do you use?

**Comment by TwistedAsylumMC** [comment]
i dont use sw it was just a suggestion for  sw servers

**Comment by Infernus101** [comment]
well, i need a function from sw plugin which tells this plugin how many games the player has won, otherwise i can't add that...

**Comment by TwistedAsylumMC** [comment]
what about this : [Skywars By Svilex](https://github.com/svilex/SkyWars-PocketMine)

**Comment by Infernus101** [comment]
outdated

**Comment by TwistedAsylumMC** [comment]
[I Updated It](https://github.com/PotatoeTrainYT/SkyWars-PocketMine)

**Comment by Infernus101** [comment]
It doesn't seem to have a function for leaderboards!
